change: write the thread and goroutine profiles into two files in threadProfile.
Since the go pprof tool can not read the combined profile file.
error: parsing profile: concatenated profiles detected

Also, we introduced the eventID to combine related profiles.